name: Unit tests

on: [push]

jobs:
  unit-test:
    strategy:
      matrix:
        go: ['1.18']
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    name: Go ${{ matrix.go }} [${{ matrix.platform }}]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
      - name: Run tests
        run: go test ./... -cover
