name: Unit tests

on: [push]

jobs:
  build:
    strategy:
      matrix:
        # go: ["1.8", "1.9", "1.10", "1.11", "1.12", "1.13", "1.14"]
        go: ["1.10", "1.11", "1.12", "1.13", "1.14"]
        platform: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.platform }}

    name: Go ${{ matrix.go }}
    steps:
      - name: Set up test environment
        shell: bash
        run: |
          echo "::set-env name=GOPATH::${{ github.workspace }}/go"
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
      - name: Run tests
        run: go test ./... -cover
