name: Unit tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # go: ["1.8", "1.9", "1.10", "1.11", "1.12", "1.13", "1.14"]
        go: ["1.13", "1.14"]

    name: Go ${{ matrix.go }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
      - run: go test ./... -cover
